# Generated by Django 6.0.1 on 2026-02-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_total_historico',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Histórico de Stock'),
        ),
    ]
