# Generated by Django 6.0.1 on 2026-02-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='codigo_seguimiento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Seguimiento'),
        ),
        migrations.AddField(
            model_name='orden',
            name='empresa_envio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa de Envío'),
        ),
    ]
