# Generated by Django 6.0.1 on 2026-02-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_orden_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='orden',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='orden',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='orden',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas de Envío'),
        ),
        migrations.AddField(
            model_name='orden',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='orden',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
    ]
