# Generated by Django 6.0.1 on 2026-02-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='datos_crudos',
            field=models.JSONField(blank=True, null=True, verbose_name='Datos Crudos Mercado Pago'),
        ),
    ]
