# Generated by Django 6.0.2 on 2026-02-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_pago_datos_crudos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='datos_crudos',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Datos Completos de MP'),
        ),
    ]
