# Generated by Django 6.0.1 on 2026-02-20 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_pago_datos_crudos'),
        ('pedidos', '0003_alter_orden_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='carrito_id',
        ),
        migrations.AddField(
            model_name='pago',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='pedidos.orden', verbose_name='Orden Asociada'),
        ),
    ]
