# Generated by Django 6.0.1 on 2026-02-21 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_remove_pago_carrito_id_pago_orden'),
        ('pedidos', '0004_orden_ciudad_orden_codigo_postal_orden_direccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('mensaje', models.TextField(verbose_name='Descripción del cambio')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pedidos.orden', verbose_name='Pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario (Admin)')),
            ],
            options={
                'verbose_name': 'Log de Compra',
                'verbose_name_plural': 'Logs de Compras',
                'ordering': ['-fecha'],
            },
        ),
    ]
