# Generated by Django 6.0.1 on 2026-02-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_compralog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compralog',
            name='mensaje',
            field=models.TextField(verbose_name='Datos de Envío y Seguimiento'),
        ),
    ]
