# Generated by Django 6.0.2 on 2026-02-21 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('tipo', models.CharField(choices=[('consulta', '❓ Consulta General'), ('queja', '😤 Queja'), ('sugerencia', '💡 Sugerencia'), ('reclamo', '📢 Reclamo'), ('otro', '📝 Otro')], default='consulta', max_length=20, verbose_name='Tipo de Mensaje')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('estado', models.CharField(choices=[('nuevo', '🔵 Nuevo'), ('leido', '👁️ Leído'), ('respondido', '✅ Respondido')], default='nuevo', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_contacto', to=settings.AUTH_USER_MODEL, verbose_name='Usuario (si está logueado)')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
